# Generated by Django 3.0.8 on 2020-08-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainskill', models.CharField(max_length=30)),
                ('subskill', models.CharField(max_length=50)),
                ('skillnames', models.CharField(max_length=100)),
                ('yn', models.BooleanField()),
                ('comment', models.CharField(max_length=100)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student')),
            ],
        ),
    ]
