# Generated by Django 3.0.8 on 2020-08-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200816_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='student',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='yn',
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yn', models.BooleanField()),
                ('comment', models.CharField(max_length=100)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
